### ISSUE TITLE
Error when piping to target-csv

### ISSUE THREAD

**Issue by allanw** [SurveyMonkey/singerio-tap-surveymonkey#1]
When I run the command `tap-surveymonkey --config config.json --properties properties.json | target-csv` I get the following error. It looks like it can't be processed and written out as a CSV due to the presence of an image property. Any help is appreciated!

```
Traceback (most recent call last):
  File "/usr/local/bin/target-csv", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/target_csv.py", line 144, in main
    config.get('destination_path', ''))
  File "/usr/local/lib/python3.7/site-packages/target_csv.py", line 59, in persist_messages
    validators[o['stream']].validate(o['record'])
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('image' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['pages']['items']['properties']['questions']['items']['properties']['answers']['properties']['choices']['items']:
    {'additionalProperties': False,
     'properties': {'description': {'$ref': '#/definitions/Description'},
                    'id': {'type': 'string'},
                    'is_na': {'type': 'boolean'},
                    'position': {'type': 'integer'},
                    'quiz_options': {'$ref': '#/definitions/ChoiceQuizOptions'},
                    'text': {'type': 'string'},
                    'visible': {'type': 'boolean'},
                    'weight': {'type': 'integer'}},
     'required': ['id', 'position', 'text', 'visible'],
     'title': 'Choice',
     'type': 'object'}
```

**Comment by allanw** [comment]
Update: Changing `additionalProperties` under the `Choice` object in the `schemas/survey_details.json` file seemed to help.

**Comment by ichensvmk** [comment]
The issue should be fixed in the latest version.
